name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Account Service Test
      run: mvn -B test --file service-account/pom.xml
    - name: Transaction Service Test
      run: mvn -B test --file service-transaction/pom.xml
    - name: Dead Letter Queue Platform Service Test
      run: mvn -B test --file service-dlq-platform/pom.xml
    - name: Account Search Service Test
      run: mvn -B test --file service-account-search/pom.xml
    - name: Authentication Service Test
      run: mvn -B test --file service-authentication/pom.xml
